# === KEYMAPS ===
map ctrl+alt+p set_background_opacity +0.025
map ctrl+alt+o set_background_opacity -0.025
map ctrl+alt+[ set_background_opacity default
map ctrl+alt+] set_background_opacity 1

map ctrl+shift+enter launch --location=hsplit
map ctrl+tab next_window
map ctrl+shift+tab previous_window
map alt+. next_window
map ctrl+alt+r load_config_file

map alt+/ combine : next_window : send_text all mk-build.sh\n : previous_window

# === KEY-UNMAPS ===
map ctrl+shift+[ noop
map ctrl+shift+] noop
