# === KEYMAPS ===
map ctrl+alt+p set_background_opacity +0.025
map ctrl+alt+o set_background_opacity -0.025
map ctrl+alt+[ set_background_opacity default
map ctrl+alt+] set_background_opacity 1

map ctrl+shift+enter launch --location=vsplit
map ctrl+tab next_window
map ctrl+shift+tab previous_window
map alt+. next_window
map ctrl+alt+r load_config_file

map ctrl+alt+left resize_window narrower 4
map ctrl+alt+right resize_window wider 4
map ctrl+alt+up resize_window taller 2
map ctrl+alt+down resize_window shorter 2

map alt+/ combine : next_window : send_text all mk-build.sh||mk\n : previous_window
map ctrl+shift+s send_text all mk'\n
map ctrl+shift+h send_text all \x13

# === KEY-UNMAPS ===
map ctrl+shift+[ noop
map ctrl+shift+] noop
