[Audio]
Volume=100

[General]
FileDialogLastLocation=file:///home/ziya/Videos/Screencasts
FooterStyle=floating
LastPlayedFile=file:///home/ziya/Downloads/Screencast_20260922_211611.mp4
LastUrl=https://vt.tiktok.com/ZSxmtVeKW/
