# === KEYMAPS ===

# [Tab-Management]
map ctrl+shift+alt+t new_tab_with_cwd
map ctrl+alt+n next_tab
map ctrl+alt+b previous_tab

# [Split-Management]
map ctrl+shift+enter launch --location=vsplit --cwd=current
map ctrl+shift+alt+enter launch --location=vsplit
map alt+. next_window
map alt+shift+. previous_window


# [Window-Resize]
map ctrl+alt+left resize_window narrower 4
map ctrl+alt+right resize_window wider 4
map ctrl+alt+up resize_window taller 2
map ctrl+alt+down resize_window shorter 2

# [Scroll]
map alt+w scroll_page_up
map alt+s scroll_page_down

# [Send-Text]
# map alt+/ send_text all mk || mk-build.sh\n
map ctrl+shift+a send_text all mk'\n
map alt+e send_text all cls\n

# [Opacity]
map ctrl+alt+p set_background_opacity +0.025
map ctrl+alt+o set_background_opacity -0.025
map ctrl+alt+[ set_background_opacity default
map ctrl+alt+] set_background_opacity 1


# [MISC]
map ctrl+shift+x command_palette
map ctrl+alt+l   load_config_file
map ctrl+shift+e save_as_session --save-only ~/.config/kitty/sessions/__saved__.conf



# === KEY-UNMAPS ===
map ctrl+shift+[ noop
map ctrl+shift+] noop

