# === GENERAL ===
confirm_os_window_close 0
sync_to_monitor yes
# repaint_delay 16
# input_delay 3

linux_display_server wayland
wayland_titlebar_color background
mouse_hide_wait 0
remember_window_size no
initial_window_width 650
initial_window_height 625



# === COLORS  ===

    # TERMINAL FOREGROUND
foreground #FFA500
foreground #cdcdd2

    # TERMINAL BACKGROUND
background #080808
background #010a07
background #01041a
background #1b021f
background #150218
background #140117

    # TERMINAL OPACITY
background_opacity 0.86
# background_blur 1
# background_opacity 0.72
# background_blur 28
dynamic_background_opacity yes

    # SELECTION COLORS
selection_background #3DA5FF
selection_foreground #ffffff

    # BORDER COLORS
inactive_border_color #002051
active_border_color #ffffff
active_border_color #00e5ff
inactive_text_alpha 0.9
    # BORDER LOGIC
draw_minimal_borders no
draw_window_borders_for_single_window no


# === BACKGROUND ===
# background_image ~/Pictures/bg/wp-petrol-sgs.png
# background_image_layout scaled
# background_opacity 0.1


# === FONT ===
font_family      family='Fira Nerd Font' style=SemiBold
font_family      family='Source Code Pro' style=SemiBold
font_family      family='Monaspace Neon Var' style=
font_family      family='JetBrainsMono Nerd Font' style=SemiBold
font_size 14.4
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
disable_ligatures cursor


# === CURSOR ===
cursor #FF00FF
cursor #21cdb3
cursor_text_color #050009

cursor_shape block
cursor_beam_thickness 13
cursor_underline_thickness 30

cursor_shape_unfocused hollow

cursor_blink_interval 0.48
cursor_stop_blinking_after 0

# === CURSOR-TRAIL ===
cursor_trail 1
cursor_trail_decay 0.08 0.28
cursor_trail_start_threshold 1
cursor_trail_color #00ffcc


# === TAB CONFIG ===
tab_bar_min_tabs 2
tab_bar_style powerline
tab_powerline_style round
bell_on_tab "🔔 "
tab_bar_align center
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_edge bottom

tab_title_template "{str(tab.active_wd).split('/')[-1]:^20}"
active_tab_title_template "{str(tab.active_wd).split('/')[-1]:^32}"

active_tab_background   #00ffd5
active_tab_foreground   #000000
active_tab_font_style bold
inactive_tab_background #797979
inactive_tab_foreground #161616
inactive_tab_foreground #19134c
inactive_tab_font_style bold-italic


# === MISC ===
scrollbar hovered
wheel_scroll_multiplier 15
scrollback_lines 10000000
scrollback_pager_history_size 100
window_padding_width 0


# === NOTIFICATION ===
bell_path none
notify_on_cmd_finish unfocused 30.0


# === THEMES ===
# include ./themes/Catppuccin-Mocha.conf
# include ./themes/Oceanic-Material.conf

# === KEYMAPS ===
include ./keymap.conf
