[Audio]
Volume=100

[General]
FileDialogLastLocation=file:///home/ziya/.local/share/Trash/files
FooterStyle=floating
LastPlayedFile=file:///home/ziya/.local/share/Trash/files/Brawl_stars_OST_-_Sirius_menu_music_(SkySound.cc).mp3
