[Audio]
Volume=100

[General]
FileDialogLastLocation=file:///home/ziya/.local/share/Trash/files
FooterStyle=floating
LastPlayedFile=file:///run/user/1000/bb54623a39974a32b40c4e8c4d5caf4a/storage/emulated/0/.trashBin/VID-20260408-WA0017.mp4
